version: '3'

services:
#ESCENARIO PRINCIPAL
  drupal:
    image: drupal:9.4-php8.0-apache-bullseye
    restart: always
    volumes:
      - drupal-data:/opt/drupal/web/
    depends_on:
      - mariadb
    ports:
      - "8081-8082:80"
    logging:
      driver: fluentd
      options:
        fluentd-async-connect: "true"
        fluentd-address: localhost:24224
        tag: drupal.logs

  mariadb:
    container_name: mariadb
    image: mariadb
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: drupal
      MYSQL_USER: drupaluser2023
      MYSQL_PASSWORD: Fl0r&c4Est4mp4d0
    volumes:
     - mariadb-data:/var/lib/mysql
#PROXY BALANCEADOR
  haproxy:
     image: haproxy:1.6
     container_name: haproxy
     restart: always
     ports:
      - 8080:80
     volumes:
      - "./haproxy/haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg:ro"
#PPANEL DE MONITORIZACIÓN
  grafana:
     image: grafana/grafana
     container_name: grafana
     ports:
      - 3000:3000
     depends_on:
       - loki
     environment:
       GF_SECURITY_ADMIN_PASSWORD: admin
       GF_SECURITY_API_KEY: eyJrIjoiTHhWbVlUR0NGUVJpTlNiSnB5SWZGdjNVNkUzOHNTMFUiLCJuIjoiYWRtaW4iLCJpZCI6MX0=
     volumes:
     - grafana-data:/var/lib/grafana
     - ./grafana/provisioning:/etc/grafana/provisioning
#SISTEMA DE ALERTAS, MONITORIZACIÓN
  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    volumes:
      - ./config/prometheus.yml:/etc/prometheus/prometheus.yml
    command:
      - --config.file=/etc/prometheus/prometheus.yml
    ports:
     - 9090:9090
  node-exporter:
    image: prom/node-exporter:latest
    restart: always
    container_name: node-exporter
    ports:
      - "9100:9100"
    volumes:
      - /etc/hostname:/etc/nodename:ro
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /mnt/docker-cluster:/mnt/docker-cluster:ro
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/TZ:ro
# SISTEMA DE RECOLECCION DE LOGS
  loki:
    image: grafana/loki:2.0.0
    container_name: loki
    volumes:
      - ./config/loki.yaml:/etc/config/loki.yaml
    ports:
      - "3100:3100"

  fluentd:
    container_name: fluentd
    image: grafana/fluent-bit-plugin-loki
    ports:
      - 24224:24224
      - 24224:24224/udp
      - 2020:2020
      - 2021:2021
    environment:
      LOKI_URL: http://loki:3100/loki/api/v1/push
    volumes:
      - ./fluent-bit/fluent-bit.conf:/fluent-bit/etc/fluent-bit.conf
# MARIADB MONITORIZACION
  mysql-exporter:
    container_name: mysql-exporter
    image: prom/mysqld-exporter
    environment:
      - DATA_SOURCE_NAME=root:root@(mariadb:3306)/
    ports:
      - "9104:9104"

volumes:
  mariadb-data:
  drupal-data:
  grafana-data:
  prometheus_data:
  drupal-backup:
